name: CD Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  deploying-dev:
    name: dev-deployment
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: |
          echo "Hey Its a test"
  deploying-pre-prod:
    name: pre-prod-deployment
    runs-on: ubuntu-latest
    needs: deploying-dev
    environment: prod
    steps:
      - name: "test"
        run: |
          echo "Hey Its a test"
      - name: "test2"
        run: |
          echo "Hey Its a test"
  deploying-prod:
    name: prod-deployment
    runs-on: ubuntu-latest
    needs: deploying-dev
    environment: prod
    steps:
      - name: "test"
        run: |
          echo "Hey Its a test"
